syntax = "proto3";

package ru.nstu.isma.contracts.v1.simulation_service;

option csharp_namespace = "Isma.Contracts.V1.SimulationService";
option go_package = "github.com/isma/contracts/v1/simulation_service";
option java_multiple_files = true;
option java_package = "ru.nstu.isma.contracts.v1.simulation_service";

/* 
 * Response containing download URL for simulation results.
 */
message GetSimulationResultResponse {
  // URL path for downloading the CSV file via HTTP
  string download_url = 2;
}
