syntax = "proto3";

package ru.nstu.isma.contracts.v1.simulation_service;

import "v1/simulation_service/messages/simulation_method_item.proto";

option csharp_namespace = "Isma.Contracts.V1.SimulationService";
option go_package = "github.com/isma/contracts/v1/simulation_service";
option java_multiple_files = true;
option java_package = "ru.nstu.isma.contracts.v1.simulation_service";

/* 
 * Response containing list of available integration methods.
 */
message ListSimulationMethodsResponse {
  // List of available methods
  repeated SimulationMethodItem methods = 1;
}
