syntax = "proto3";

package ru.nstu.isma.contracts.v1.compiler_service;

option csharp_namespace = "Isma.Contracts.V1.CompilerService";
option go_package = "github.com/isma/contracts/v1/compiler_service";
option java_multiple_files = true;
option java_package = "ru.nstu.isma.contracts.v1.compiler_service";

enum TokenKind {
  TOKEN_KIND_UNSPECIFIED = 0;
  TOKEN_KIND_KEYWORD = 1;
  TOKEN_KIND_COMMENT = 2;
  TOKEN_KIND_NUMBER = 3;
  TOKEN_KIND_TEXT = 4;
}

message SyntaxToken {
  int32 start = 1;
  int32 length = 2;
  TokenKind kind = 3;
}

message HighlightResponse {
  repeated SyntaxToken tokens = 1;
}
