syntax = "proto3";

package ru.nstu.isma.contracts.v1.compiler_service;

import "v1/compiler_service/messages/compile_response.proto";

option csharp_namespace = "Isma.Contracts.V1.CompilerService";
option go_package = "github.com/isma/contracts/v1/compiler_service";
option java_multiple_files = true;
option java_package = "ru.nstu.isma.contracts.v1.compiler_service";

message ValidateRequest {
  string lisma_source_code = 1;
}

message ValidateResponse {
  repeated CompilationError errors = 1;
  repeated string warnings = 2;
}
